backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - label: "Contact Settings"
        name: "contact_settings"
        file: "content/contact_settings.md"
        editor:
          preview: false
        fields:
          - { name: email, label: Email address, widget: string }
          - { name: phone, label: Phone number, widget: string }
          - { name: facebook, label: Facebook username, widget: string }
      - label: "Social Settings"
        name: "social_settings"
        file: "content/social_settings.md"
        editor:
          preview: false
        fields:
          - { name: facebook, label: Facebook URL, widget: string }
          - { name: github, label: GitHub URL, widget: string }
          - { name: instagram, label: Instagram URL, widget: string }
  - name: pages
    label: Pages
    files:
      - label: "Hero Section"
        name: "hero"
        file: "content/hero.md"
        fields:
          - { name: hero_image, label: Hero Image, widget: image }
          - { name: lead, label: Lead, widget: text }
          - { name: button_text, label: Button Text, widget: string }
      - label: "Tuts Section"
        name: "tuts"
        file: "content/tuts.md"
        editor:
          preview: false
        fields:
          - { name: heading, label: Heading, widget: string }
          - { name: lead, label: Lead, widget: text }
          - { name: followup_heading, label: Follow-up Heading, widget: string }
          - { name: followup_text, label: Follow-up Text, widget: text }
          - { name: followup_button_text, label: Follow-up Button Text, widget: string }
      - label: "Tuts Pages"
        name: "tuts_pages"
        file: "content/tuts_pages.md"
        editor:
          preview: false
        fields:
          - { name: followup_heading, label: Follow-up Heading, widget: string }
          - { name: followup_text, label: Follow-up Text, widget: text }
          - { name: followup_facebook_button_text, label: Follow-up Facebook Button Text, widget: string }
      - label: "Contact Section"
        name: "contact"
        file: "content/contact.md"
        editor:
          preview: false
        fields:
          - { name: heading, label: Heading, widget: string }
          - { name: lead, label: Lead, widget: text }
          - { name: contact_form_intro, label: Contact Form Intro, widget: text }
          - { name: send_button_text, label: Send Button Text, widget: string }
  - name: tutorials
    label: Tutorials
    folder: tutorials
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { name: featured_image, label: Image, widget: image }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: intro_text, label: Intro Text }
      - { name: tags, label: Tags, widget: list, default: ['unspecified']}
      - { name: body, label: Body, widget: markdown }